

# Site settings
title: Nicole Drakos
email: nicoledrakos@gmail.com
url: "https://ndrakos.github.io/blog/" # the base hostname & protocol for your site
twitter_username: nicoledrakos
github_username:  ndrakos


markdown: kramdown
theme: jekyll-theme-dinky

# Build settings
mathjax: true
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: "" # empty string for all files
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            path: ""
            type: "draft"
        values:
            layout: "post"
